### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Heikrana** [Elixir-ABESEC/website#14]
**Feature required :** Page Footer

Sample layout is available on Discord → Elixir Server → elixir-website channel.
Create a Footer with placeholder links and **Signup** option for the newsletter.
This is a 2 part issue, this one only handles the **CSS** part. So, don't worry adding any logic.

**Note**
First comment on this issue and when it gets assigned to you, then only start working on it.
Fork this repo if you haven't already, then make your own branch. When the changes are finalized, simply merge into main and create a PR on this repo.

**Comment by pulkit-30** [comment]
Please assign me this issue.
